### ISSUE TITLE
Deploy clrfund to Optimism testnet

### ISSUE THREAD

**Issue by slgraham** [clrfund/monorepo#293] opened 2021-03-02 01:57 UTC
With the goal of surfacing compatibility issues or any other issues:

1. Deploy clr.fund to the Optimism testnet 
2. Run a test round
3. Measure gas costs for (1) and (2)

**Comment by slgraham** [comment] 2021-03-02 01:58
Marked as a `good first issue` because this will be a good way for a new technical contributor to learn how clr.fund works.

**Comment by xuhcc** [comment] 2021-04-23 10:09
Seems to be a duplicate of #260

**Closed** 2021-06-22 19:20 UTC
Labels: good first issue
